language: java
jdk: oraclejdk8
install: true
before_script:
 - echo "Starting build"
script:
 - mvn clean package
deploy:
 -
   on:
     branch: release
   provider: bintray
   skip_cleanup: true
   file: target/bin/bintray.json
   user: bigtheta-dev
   key: $BINTRAY_API_KEY